name: Draft new release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Kind of version you want to release. (Possible values: patch, minor, major)'
        options:
        - patch
        - minor
        - major
        required: true
        default: patch

permissions:
  contents: read
  pull-requests: write

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: [ nebula-runners ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
